name: 'github-vulnerability-alert-list'
description: 'Get github vulnerability alerts'
author: 'mongolyy'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
